### ISSUE TITLE
您好，请问这个项目的意义（目的）是？

### ISSUE THREAD

**Issue by ZsIsMe** [samlaudev/ElemeProject#1]
不知道我的表述是否正确，这个项目的意义是什么？是为我们展示app开发的流程，还是实际开发出一个app出来？
如果是实际开发出一个app，那么服务器端怎么解决呢？
还有，readme里面的john me部分还没写呢，，

**Comment by samlaudev** [comment]
实际开发一个app，在开发app过程中，总结开发经验，分享给大家！其实饿了么有开放api，所有服务端不用自己写！

**Comment by xohozu** [comment]
这个项目可以参与吗
